### ISSUE TITLE
can't access phpmyadmin after restart lando.

### ISSUE THREAD

**Issue by 0MAL** [lando/phpmyadmin#14]
I'm new to lando.
I installed phpmyadmin according to the lando manual, then, I could access phpmyadmin via browser.
But after I modified my_custom.cnf in ./lando/config/mysql/, I restarted myApp from Docker Desktop and I restarted land using the  command, lando stop and  land start, vital info listed the url for new phpmyadmin, and I opened the url by browser then, error displayed like "can't connect to the server(localhost)" and phpmyadmin isn't shown.

**Comment by 0MAL** [comment]
Sorry, I may be wrong.
The issue occurred because when I lando-starting, I noticed the my_custom.cnf in a editor suddenly reset so that I undo the latest modification and re-save the my_custom.cnf file during the lando-starting...That might be the culprit because, I retried to use phpmyadmin and at that time, I didn't undo the reset file, then I can use phpmyadmin without problems.

**Comment by SpiralBrad** [comment]
@lando ...9 months later and this issue hasn't been closed yet?
